"""
Email Notifier — AI Investment Fund
Sends weekly PDF report via Gmail (free, no subscription needed).

Setup:
  1. Gmail → Settings → Security → 2-Step Verification (enable)
  2. Gmail → Settings → Security → App Passwords → Create one named "InvestFund"
  3. Add to .env:
        EMAIL_SENDER=tumail@gmail.com
        EMAIL_APP_PASSWORD=xxxx xxxx xxxx xxxx   (16-char App Password, no spaces)
        EMAIL_RECIPIENT=tumail@gmail.com           (can be same or different)
"""
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text    import MIMEText
from email.mime.base    import MIMEBase
from email              import encoders
from pathlib            import Path
from datetime           import datetime
from dotenv             import load_dotenv

load_dotenv()

SENDER    = os.getenv("EMAIL_SENDER", "")
APP_PASS  = os.getenv("EMAIL_APP_PASSWORD", "")
RECIPIENT = os.getenv("EMAIL_RECIPIENT", "")


def _is_configured() -> bool:
    return bool(SENDER and APP_PASS and RECIPIENT and
                APP_PASS != "your_gmail_app_password_here")


def send_email(subject: str, body_html: str, pdf_path: Path = None) -> bool:
    """Send an HTML email with optional PDF attachment via Gmail."""
    if not _is_configured():
        print("[Email] Not configured — skipping")
        return False

    try:
        msg = MIMEMultipart("mixed")
        msg["From"]    = f"AI Investment Fund <{SENDER}>"
        msg["To"]      = RECIPIENT
        msg["Subject"] = subject

        # HTML body
        msg.attach(MIMEText(body_html, "html"))

        # Attach PDF if provided
        if pdf_path and pdf_path.exists():
            with open(pdf_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition",
                            f"attachment; filename={pdf_path.name}")
            msg.attach(part)

        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(SENDER, APP_PASS)
            server.sendmail(SENDER, RECIPIENT, msg.as_string())

        print(f"[Email] Sent: {subject}")
        return True

    except Exception as e:
        print(f"[Email] Error: {e}")
        return False


# ─── Pre-built email templates ─────────────────────────────────────────────────

def _base_html(content: str) -> str:
    """Wrap content in dark-theme HTML email template."""
    return f"""
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #0a0e1a; color: #f1f5f9; margin: 0; padding: 0; }}
  .container {{ max-width: 600px; margin: 0 auto; padding: 24px; }}
  .header {{ background: linear-gradient(135deg, #1e1b4b, #111827);
             border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 20px; }}
  .header h1 {{ color: #3b82f6; font-size: 22px; margin: 0; }}
  .header p {{ color: #94a3b8; font-size: 13px; margin: 6px 0 0; }}
  .card {{ background: #1f2937; border-radius: 10px; padding: 18px; margin-bottom: 14px; }}
  .card h3 {{ color: #3b82f6; font-size: 14px; margin: 0 0 8px; text-transform: uppercase; }}
  .buy  {{ border-left: 4px solid #10b981; }}
  .sell {{ border-left: 4px solid #ef4444; }}
  .watch{{ border-left: 4px solid #3b82f6; }}
  .metric {{ display: inline-block; background: #111827; padding: 6px 12px;
             border-radius: 6px; margin: 4px; font-size: 13px; }}
  .metric b {{ color: #f1f5f9; }}
  .metric span {{ color: #94a3b8; font-size: 11px; }}
  .green {{ color: #10b981; font-weight: bold; }}
  .red   {{ color: #ef4444; font-weight: bold; }}
  .gold  {{ color: #f59e0b; font-weight: bold; }}
  .footer {{ text-align: center; color: #6b7280; font-size: 11px; margin-top: 24px; }}
  a {{ color: #3b82f6; }}
</style></head>
<body><div class="container">
  <div class="header">
    <h1>AI INVESTMENT FUND</h1>
    <p>Buffett × Lynch Hybrid Strategy</p>
  </div>
  {content}
  <div class="footer">
    This is automated investment intelligence, not financial advice.<br>
    Generated by AI Investment Fund &mdash; {datetime.now().strftime('%Y-%m-%d %H:%M')}
  </div>
</div></body></html>"""


def email_weekly_report(pdf_path: Path, regions: int, picks: int, top_pick: str):
    """Send the weekly PDF report as email attachment."""
    date_str = datetime.now().strftime("%d %B %Y")
    content = f"""
    <div class="card">
      <h3>Weekly Report — {date_str}</h3>
      <p style="color:#94a3b8">Your weekly global investment intelligence report is attached.</p>
      <br>
      <div class="metric"><span>Regions</span><br><b>{regions}/6</b></div>
      <div class="metric"><span>Opportunities</span><br><b>{picks}</b></div>
      <div class="metric"><span>Top Pick</span><br><b>{top_pick}</b></div>
    </div>
    <p style="color:#94a3b8;font-size:13px">
      Open the attached PDF for the full analysis including global markets, 
      commodities, FX rates, real estate opportunities, and business ideas.
    </p>"""

    send_email(
        subject=f"Investment Fund — Weekly Report {date_str}",
        body_html=_base_html(content),
        pdf_path=pdf_path,
    )


def email_buy_alert(ticker: str, company: str, price: float, target: float,
                    mos_pct: float, score: int, reason: str):
    """Send a BUY signal email."""
    potential = round((target - price) / price * 100, 1)
    content = f"""
    <div class="card buy">
      <h3>🟢 BUY SIGNAL — {ticker}</h3>
      <p style="color:#f1f5f9;font-size:15px;font-weight:bold">{company}</p>
      <div class="metric"><span>Entry Price</span><br><b>${price:,.2f}</b></div>
      <div class="metric"><span>12M Target</span><br><b class="green">${target:,.2f} (+{potential}%)</b></div>
      <div class="metric"><span>Margin of Safety</span><br><b class="green">{mos_pct:.0f}%</b></div>
      <div class="metric"><span>Hybrid Score</span><br><b class="gold">{score}/100</b></div>
      <br><br>
      <p style="color:#94a3b8"><b>Investment Thesis:</b> {reason}</p>
    </div>"""
    send_email(f"BUY Signal: {ticker} — ${price:,.2f}", _base_html(content))


def email_sell_alert(ticker: str, company: str, price: float,
                     entry_price: float, gain_pct: float, reason: str):
    """Send a SELL / take-profit email."""
    css_class = "sell"
    color_class = "green" if gain_pct >= 0 else "red"
    content = f"""
    <div class="card {css_class}">
      <h3>{'💚 TAKE PROFIT' if gain_pct >= 0 else '🔴 STOP LOSS'} — {ticker}</h3>
      <p style="color:#f1f5f9;font-size:15px;font-weight:bold">{company}</p>
      <div class="metric"><span>Sell Price</span><br><b>${price:,.2f}</b></div>
      <div class="metric"><span>Entry Price</span><br><b>${entry_price:,.2f}</b></div>
      <div class="metric"><span>Return</span><br><b class="{color_class}">{gain_pct:+.1f}%</b></div>
      <br><br>
      <p style="color:#94a3b8"><b>Reason:</b> {reason}</p>
    </div>"""
    send_email(f"{'SELL' if gain_pct >= 0 else 'STOP'}: {ticker} ({gain_pct:+.1f}%)", _base_html(content))
